version: '3'

services:
  api:
    build: .
    ports:
      - "5300:80"    
    environment:
      - MONGO_URL=db
      - MONGO_PORT=27017
  db:
    image: mvertes/alpine-mongo
    ports:
    - "27017:27017"