name: Validate merge request

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Install dotCover
        run: dotnet tool install JetBrains.dotCover.GlobalTool -g
      - name: Calculate coverage
        run: dotnet dotcover test --dcReportType=XML --dcFilters=-:module=GhostNetwork.Publications.Domain.UnitTest
      - name: Dispaly total coverage
        run: grep -o 'CoveragePercent="[^"]*"' -m 1 dotCover.Output.xml | cut -c 18-19

  api-test:
    needs: unit-test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: ./tests/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run service instance
        run: docker-compose up -d
      - name: Test with pytest
        working-directory: ./tests/api
        run: pytest
      - run: docker ps -a
        if: ${{ failure() }}
